#!/bin/sh -e
VERSION="$1"

if [ -z "$VERSION" ]
then
    echo "You need to specify a version (ex. '1.0.0')"
    exit 1
fi

echo "Updating manifest.json version"
sed -E -i "" "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$VERSION\"/g" manifest.json
git add manifest.json
git commit -m "Version $VERSION"
git tag -a "v$VERSION" -m "v$VERSION"

echo "Building JS"
npm run build

echo "Zipping extension"
rm -f pullapprove-browser-extension.zip
zip -r pullapprove-browser-extension.zip dist img LICENSE manifest.json

# TODO upload to chrome?

git push && git push --tags

gh release create "v$VERSION" pullapprove-browser-extension.zip
