name: test

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run pre-commit
    - run: yarn run build
